title: My random site
author: Hristo Kamenov
email: hkamenov123@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the description of my site. Nothing interesting for now...

# social links
twitter_username: revanee
github_username:  revanee

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-hacker